// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: wealthflow/v1/service.proto

package wealthflowv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WealthFlowService_RecordInflow_FullMethodName     = "/wealthflow.v1.WealthFlowService/RecordInflow"
	WealthFlowService_LogExpense_FullMethodName       = "/wealthflow.v1.WealthFlowService/LogExpense"
	WealthFlowService_UpdateInvestment_FullMethodName = "/wealthflow.v1.WealthFlowService/UpdateInvestment"
)

// WealthFlowServiceClient is the client API for WealthFlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WealthFlowService provides RPCs for managing financial transactions
type WealthFlowServiceClient interface {
	// RecordInflow records an income/inflow transaction
	// If is_external is true, triggers the Split Rule Engine to distribute funds
	RecordInflow(ctx context.Context, in *RecordInflowRequest, opts ...grpc.CallOption) (*RecordInflowResponse, error)
	// LogExpense records an expense transaction with double-layer accounting
	// Creates entries in both Physical and Virtual layers
	LogExpense(ctx context.Context, in *LogExpenseRequest, opts ...grpc.CallOption) (*LogExpenseResponse, error)
	// UpdateInvestment updates the market value for an investment bucket
	// Inserts a new entry into market_value_history (does NOT create a transaction)
	UpdateInvestment(ctx context.Context, in *UpdateInvestmentRequest, opts ...grpc.CallOption) (*UpdateInvestmentResponse, error)
}

type wealthFlowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWealthFlowServiceClient(cc grpc.ClientConnInterface) WealthFlowServiceClient {
	return &wealthFlowServiceClient{cc}
}

func (c *wealthFlowServiceClient) RecordInflow(ctx context.Context, in *RecordInflowRequest, opts ...grpc.CallOption) (*RecordInflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordInflowResponse)
	err := c.cc.Invoke(ctx, WealthFlowService_RecordInflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wealthFlowServiceClient) LogExpense(ctx context.Context, in *LogExpenseRequest, opts ...grpc.CallOption) (*LogExpenseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogExpenseResponse)
	err := c.cc.Invoke(ctx, WealthFlowService_LogExpense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wealthFlowServiceClient) UpdateInvestment(ctx context.Context, in *UpdateInvestmentRequest, opts ...grpc.CallOption) (*UpdateInvestmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInvestmentResponse)
	err := c.cc.Invoke(ctx, WealthFlowService_UpdateInvestment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WealthFlowServiceServer is the server API for WealthFlowService service.
// All implementations must embed UnimplementedWealthFlowServiceServer
// for forward compatibility.
//
// WealthFlowService provides RPCs for managing financial transactions
type WealthFlowServiceServer interface {
	// RecordInflow records an income/inflow transaction
	// If is_external is true, triggers the Split Rule Engine to distribute funds
	RecordInflow(context.Context, *RecordInflowRequest) (*RecordInflowResponse, error)
	// LogExpense records an expense transaction with double-layer accounting
	// Creates entries in both Physical and Virtual layers
	LogExpense(context.Context, *LogExpenseRequest) (*LogExpenseResponse, error)
	// UpdateInvestment updates the market value for an investment bucket
	// Inserts a new entry into market_value_history (does NOT create a transaction)
	UpdateInvestment(context.Context, *UpdateInvestmentRequest) (*UpdateInvestmentResponse, error)
	mustEmbedUnimplementedWealthFlowServiceServer()
}

// UnimplementedWealthFlowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWealthFlowServiceServer struct{}

func (UnimplementedWealthFlowServiceServer) RecordInflow(context.Context, *RecordInflowRequest) (*RecordInflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordInflow not implemented")
}
func (UnimplementedWealthFlowServiceServer) LogExpense(context.Context, *LogExpenseRequest) (*LogExpenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogExpense not implemented")
}
func (UnimplementedWealthFlowServiceServer) UpdateInvestment(context.Context, *UpdateInvestmentRequest) (*UpdateInvestmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInvestment not implemented")
}
func (UnimplementedWealthFlowServiceServer) mustEmbedUnimplementedWealthFlowServiceServer() {}
func (UnimplementedWealthFlowServiceServer) testEmbeddedByValue()                           {}

// UnsafeWealthFlowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WealthFlowServiceServer will
// result in compilation errors.
type UnsafeWealthFlowServiceServer interface {
	mustEmbedUnimplementedWealthFlowServiceServer()
}

func RegisterWealthFlowServiceServer(s grpc.ServiceRegistrar, srv WealthFlowServiceServer) {
	// If the following call pancis, it indicates UnimplementedWealthFlowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WealthFlowService_ServiceDesc, srv)
}

func _WealthFlowService_RecordInflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordInflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WealthFlowServiceServer).RecordInflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WealthFlowService_RecordInflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WealthFlowServiceServer).RecordInflow(ctx, req.(*RecordInflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WealthFlowService_LogExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogExpenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WealthFlowServiceServer).LogExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WealthFlowService_LogExpense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WealthFlowServiceServer).LogExpense(ctx, req.(*LogExpenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WealthFlowService_UpdateInvestment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInvestmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WealthFlowServiceServer).UpdateInvestment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WealthFlowService_UpdateInvestment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WealthFlowServiceServer).UpdateInvestment(ctx, req.(*UpdateInvestmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WealthFlowService_ServiceDesc is the grpc.ServiceDesc for WealthFlowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WealthFlowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wealthflow.v1.WealthFlowService",
	HandlerType: (*WealthFlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordInflow",
			Handler:    _WealthFlowService_RecordInflow_Handler,
		},
		{
			MethodName: "LogExpense",
			Handler:    _WealthFlowService_LogExpense_Handler,
		},
		{
			MethodName: "UpdateInvestment",
			Handler:    _WealthFlowService_UpdateInvestment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wealthflow/v1/service.proto",
}
