// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: wealthflow/v1/service.proto

package wealthflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BucketType represents the type of bucket in the system
type BucketType int32

const (
	BucketType_BUCKET_TYPE_UNSPECIFIED BucketType = 0
	BucketType_BUCKET_TYPE_PHYSICAL    BucketType = 1
	BucketType_BUCKET_TYPE_VIRTUAL     BucketType = 2
	BucketType_BUCKET_TYPE_INCOME      BucketType = 3
	BucketType_BUCKET_TYPE_EXPENSE     BucketType = 4
	BucketType_BUCKET_TYPE_EQUITY      BucketType = 5
)

// Enum value maps for BucketType.
var (
	BucketType_name = map[int32]string{
		0: "BUCKET_TYPE_UNSPECIFIED",
		1: "BUCKET_TYPE_PHYSICAL",
		2: "BUCKET_TYPE_VIRTUAL",
		3: "BUCKET_TYPE_INCOME",
		4: "BUCKET_TYPE_EXPENSE",
		5: "BUCKET_TYPE_EQUITY",
	}
	BucketType_value = map[string]int32{
		"BUCKET_TYPE_UNSPECIFIED": 0,
		"BUCKET_TYPE_PHYSICAL":    1,
		"BUCKET_TYPE_VIRTUAL":     2,
		"BUCKET_TYPE_INCOME":      3,
		"BUCKET_TYPE_EXPENSE":     4,
		"BUCKET_TYPE_EQUITY":      5,
	}
)

func (x BucketType) Enum() *BucketType {
	p := new(BucketType)
	*p = x
	return p
}

func (x BucketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BucketType) Descriptor() protoreflect.EnumDescriptor {
	return file_wealthflow_v1_service_proto_enumTypes[0].Descriptor()
}

func (BucketType) Type() protoreflect.EnumType {
	return &file_wealthflow_v1_service_proto_enumTypes[0]
}

func (x BucketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BucketType.Descriptor instead.
func (BucketType) EnumDescriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{0}
}

// RecordInflowRequest represents an income/inflow transaction
type RecordInflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount as a decimal string (e.g., "1000.50") to preserve precision
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Description of the inflow transaction
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Source bucket ID (UUID as string) - typically an Income or Physical bucket
	SourceBucketId string `protobuf:"bytes,3,opt,name=source_bucket_id,json=sourceBucketId,proto3" json:"source_bucket_id,omitempty"`
	// If true, this is an external inflow that triggers Split Rule Engine
	IsExternal bool `protobuf:"varint,4,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"`
	// Optional: Transaction date (defaults to server time if not provided)
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordInflowRequest) Reset() {
	*x = RecordInflowRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordInflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordInflowRequest) ProtoMessage() {}

func (x *RecordInflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordInflowRequest.ProtoReflect.Descriptor instead.
func (*RecordInflowRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RecordInflowRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RecordInflowRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecordInflowRequest) GetSourceBucketId() string {
	if x != nil {
		return x.SourceBucketId
	}
	return ""
}

func (x *RecordInflowRequest) GetIsExternal() bool {
	if x != nil {
		return x.IsExternal
	}
	return false
}

func (x *RecordInflowRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// RecordInflowResponse returns the created transaction details
type RecordInflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID (UUID as string)
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Timestamp when the transaction was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordInflowResponse) Reset() {
	*x = RecordInflowResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordInflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordInflowResponse) ProtoMessage() {}

func (x *RecordInflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordInflowResponse.ProtoReflect.Descriptor instead.
func (*RecordInflowResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecordInflowResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecordInflowResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// LogExpenseRequest represents an expense transaction
type LogExpenseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount as a decimal string (e.g., "25.99") to preserve precision
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Description of the expense
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Virtual bucket ID (UUID as string) - the virtual bucket being debited
	VirtualBucketId string `protobuf:"bytes,3,opt,name=virtual_bucket_id,json=virtualBucketId,proto3" json:"virtual_bucket_id,omitempty"`
	// Category bucket ID (UUID as string) - the external expense category
	CategoryBucketId string `protobuf:"bytes,4,opt,name=category_bucket_id,json=categoryBucketId,proto3" json:"category_bucket_id,omitempty"`
	// Optional: Override the physical bucket to credit
	// If not provided, uses the parent physical bucket of virtual_bucket_id
	PhysicalBucketOverrideId string `protobuf:"bytes,5,opt,name=physical_bucket_override_id,json=physicalBucketOverrideId,proto3" json:"physical_bucket_override_id,omitempty"`
	// Optional: Transaction date (defaults to server time if not provided)
	Date          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogExpenseRequest) Reset() {
	*x = LogExpenseRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogExpenseRequest) ProtoMessage() {}

func (x *LogExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogExpenseRequest.ProtoReflect.Descriptor instead.
func (*LogExpenseRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogExpenseRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LogExpenseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LogExpenseRequest) GetVirtualBucketId() string {
	if x != nil {
		return x.VirtualBucketId
	}
	return ""
}

func (x *LogExpenseRequest) GetCategoryBucketId() string {
	if x != nil {
		return x.CategoryBucketId
	}
	return ""
}

func (x *LogExpenseRequest) GetPhysicalBucketOverrideId() string {
	if x != nil {
		return x.PhysicalBucketOverrideId
	}
	return ""
}

func (x *LogExpenseRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// LogExpenseResponse returns the created transaction details
type LogExpenseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID (UUID as string)
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Timestamp when the transaction was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Physical bucket ID that was actually credited (useful when override was used)
	PhysicalBucketId string `protobuf:"bytes,3,opt,name=physical_bucket_id,json=physicalBucketId,proto3" json:"physical_bucket_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogExpenseResponse) Reset() {
	*x = LogExpenseResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogExpenseResponse) ProtoMessage() {}

func (x *LogExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogExpenseResponse.ProtoReflect.Descriptor instead.
func (*LogExpenseResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *LogExpenseResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *LogExpenseResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LogExpenseResponse) GetPhysicalBucketId() string {
	if x != nil {
		return x.PhysicalBucketId
	}
	return ""
}

// UpdateInvestmentRequest represents a market value update for an investment bucket
type UpdateInvestmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket ID (UUID as string) - must be an EQUITY type bucket
	BucketId string `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	// Market value as a decimal string (e.g., "650.00") to preserve precision
	MarketValue string `protobuf:"bytes,2,opt,name=market_value,json=marketValue,proto3" json:"market_value,omitempty"`
	// Optional: Date of the market value (defaults to server time if not provided)
	Date          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvestmentRequest) Reset() {
	*x = UpdateInvestmentRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvestmentRequest) ProtoMessage() {}

func (x *UpdateInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvestmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateInvestmentRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

func (x *UpdateInvestmentRequest) GetMarketValue() string {
	if x != nil {
		return x.MarketValue
	}
	return ""
}

func (x *UpdateInvestmentRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// UpdateInvestmentResponse confirms the market value update
type UpdateInvestmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Market value history entry ID (UUID as string)
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	// Timestamp when the entry was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvestmentResponse) Reset() {
	*x = UpdateInvestmentResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvestmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvestmentResponse) ProtoMessage() {}

func (x *UpdateInvestmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvestmentResponse.ProtoReflect.Descriptor instead.
func (*UpdateInvestmentResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateInvestmentResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *UpdateInvestmentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ListBucketsRequest represents a request to list buckets
type ListBucketsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: Filter by bucket type (e.g., "PHYSICAL", "VIRTUAL", "INCOME", "EXPENSE", "EQUITY", "SYSTEM")
	BucketType    string `protobuf:"bytes,1,opt,name=bucket_type,json=bucketType,proto3" json:"bucket_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsRequest) Reset() {
	*x = ListBucketsRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsRequest) ProtoMessage() {}

func (x *ListBucketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsRequest.ProtoReflect.Descriptor instead.
func (*ListBucketsRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListBucketsRequest) GetBucketType() string {
	if x != nil {
		return x.BucketType
	}
	return ""
}

// ListBucketsResponse returns a list of buckets
type ListBucketsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of buckets
	Buckets       []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsResponse) Reset() {
	*x = ListBucketsResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsResponse) ProtoMessage() {}

func (x *ListBucketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsResponse.ProtoReflect.Descriptor instead.
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListBucketsResponse) GetBuckets() []*Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// Bucket represents a bucket in the system
type Bucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket ID (UUID as string)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Bucket name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Bucket type
	Type BucketType `protobuf:"varint,3,opt,name=type,proto3,enum=wealthflow.v1.BucketType" json:"type,omitempty"`
	// Current balance as a decimal string (e.g., "1000.50") to preserve precision
	CurrentBalance string `protobuf:"bytes,4,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	// Optional: Parent physical bucket ID (UUID as string) - only set for VIRTUAL buckets
	ParentId      string `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bucket) Reset() {
	*x = Bucket{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bucket.ProtoReflect.Descriptor instead.
func (*Bucket) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *Bucket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bucket) GetType() BucketType {
	if x != nil {
		return x.Type
	}
	return BucketType_BUCKET_TYPE_UNSPECIFIED
}

func (x *Bucket) GetCurrentBalance() string {
	if x != nil {
		return x.CurrentBalance
	}
	return ""
}

func (x *Bucket) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

// ListTransactionsRequest represents a request to list transactions
type ListTransactionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of transactions to return
	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Number of transactions to skip (for pagination)
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// Optional: Filter by bucket ID (UUID as string) - returns transactions involving this bucket
	BucketId      string `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTransactionsRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

// ListTransactionsResponse returns a list of transactions
type ListTransactionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of transactions
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	// Total count of transactions (for pagination)
	TotalCount    int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Transaction represents a transaction in the system
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID (UUID as string)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Transaction description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Transaction amount as a decimal string (e.g., "100.50") - represents the total transaction amount
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// Transaction date
	Date *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	// Whether this is an external inflow transaction
	IsExternal    bool `protobuf:"varint,5,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Transaction) GetIsExternal() bool {
	if x != nil {
		return x.IsExternal
	}
	return false
}

// GetNetWorthRequest represents a request to get net worth
type GetNetWorthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetWorthRequest) Reset() {
	*x = GetNetWorthRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetWorthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetWorthRequest) ProtoMessage() {}

func (x *GetNetWorthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetWorthRequest.ProtoReflect.Descriptor instead.
func (*GetNetWorthRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{12}
}

// GetNetWorthResponse returns the calculated net worth
type GetNetWorthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total net worth as a decimal string (liquidity + equity)
	TotalNetWorth string `protobuf:"bytes,1,opt,name=total_net_worth,json=totalNetWorth,proto3" json:"total_net_worth,omitempty"`
	// Liquidity (sum of PHYSICAL bucket balances) as a decimal string
	Liquidity string `protobuf:"bytes,2,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	// Equity (sum of EQUITY bucket market values) as a decimal string
	Equity        string `protobuf:"bytes,3,opt,name=equity,proto3" json:"equity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetWorthResponse) Reset() {
	*x = GetNetWorthResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetWorthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetWorthResponse) ProtoMessage() {}

func (x *GetNetWorthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetWorthResponse.ProtoReflect.Descriptor instead.
func (*GetNetWorthResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetNetWorthResponse) GetTotalNetWorth() string {
	if x != nil {
		return x.TotalNetWorth
	}
	return ""
}

func (x *GetNetWorthResponse) GetLiquidity() string {
	if x != nil {
		return x.Liquidity
	}
	return ""
}

func (x *GetNetWorthResponse) GetEquity() string {
	if x != nil {
		return x.Equity
	}
	return ""
}

// GetBucketRequest represents a request to get a bucket by ID
type GetBucketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bucket ID (UUID as string)
	BucketId      string `protobuf:"bytes,1,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketRequest) Reset() {
	*x = GetBucketRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketRequest) ProtoMessage() {}

func (x *GetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketRequest.ProtoReflect.Descriptor instead.
func (*GetBucketRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetBucketRequest) GetBucketId() string {
	if x != nil {
		return x.BucketId
	}
	return ""
}

// GetBucketResponse returns a single bucket
type GetBucketResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested bucket
	Bucket        *Bucket `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketResponse) Reset() {
	*x = GetBucketResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketResponse) ProtoMessage() {}

func (x *GetBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketResponse.ProtoReflect.Descriptor instead.
func (*GetBucketResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetBucketResponse) GetBucket() *Bucket {
	if x != nil {
		return x.Bucket
	}
	return nil
}

var File_wealthflow_v1_service_proto protoreflect.FileDescriptor

const file_wealthflow_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bwealthflow/v1/service.proto\x12\rwealthflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\x13RecordInflowRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x10source_bucket_id\x18\x03 \x01(\tR\x0esourceBucketId\x12\x1f\n" +
	"\vis_external\x18\x04 \x01(\bR\n" +
	"isExternal\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"x\n" +
	"\x14RecordInflowResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x96\x02\n" +
	"\x11LogExpenseRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11virtual_bucket_id\x18\x03 \x01(\tR\x0fvirtualBucketId\x12,\n" +
	"\x12category_bucket_id\x18\x04 \x01(\tR\x10categoryBucketId\x12=\n" +
	"\x1bphysical_bucket_override_id\x18\x05 \x01(\tR\x18physicalBucketOverrideId\x12.\n" +
	"\x04date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xa4\x01\n" +
	"\x12LogExpenseResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12,\n" +
	"\x12physical_bucket_id\x18\x03 \x01(\tR\x10physicalBucketId\"\x89\x01\n" +
	"\x17UpdateInvestmentRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\x12!\n" +
	"\fmarket_value\x18\x02 \x01(\tR\vmarketValue\x12.\n" +
	"\x04date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"p\n" +
	"\x18UpdateInvestmentResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"5\n" +
	"\x12ListBucketsRequest\x12\x1f\n" +
	"\vbucket_type\x18\x01 \x01(\tR\n" +
	"bucketType\"F\n" +
	"\x13ListBucketsResponse\x12/\n" +
	"\abuckets\x18\x01 \x03(\v2\x15.wealthflow.v1.BucketR\abuckets\"\xa1\x01\n" +
	"\x06Bucket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.wealthflow.v1.BucketTypeR\x04type\x12'\n" +
	"\x0fcurrent_balance\x18\x04 \x01(\tR\x0ecurrentBalance\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\"d\n" +
	"\x17ListTransactionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1b\n" +
	"\tbucket_id\x18\x03 \x01(\tR\bbucketId\"{\n" +
	"\x18ListTransactionsResponse\x12>\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1a.wealthflow.v1.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa8\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12.\n" +
	"\x04date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x1f\n" +
	"\vis_external\x18\x05 \x01(\bR\n" +
	"isExternal\"\x14\n" +
	"\x12GetNetWorthRequest\"s\n" +
	"\x13GetNetWorthResponse\x12&\n" +
	"\x0ftotal_net_worth\x18\x01 \x01(\tR\rtotalNetWorth\x12\x1c\n" +
	"\tliquidity\x18\x02 \x01(\tR\tliquidity\x12\x16\n" +
	"\x06equity\x18\x03 \x01(\tR\x06equity\"/\n" +
	"\x10GetBucketRequest\x12\x1b\n" +
	"\tbucket_id\x18\x01 \x01(\tR\bbucketId\"B\n" +
	"\x11GetBucketResponse\x12-\n" +
	"\x06bucket\x18\x01 \x01(\v2\x15.wealthflow.v1.BucketR\x06bucket*\xa5\x01\n" +
	"\n" +
	"BucketType\x12\x1b\n" +
	"\x17BUCKET_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14BUCKET_TYPE_PHYSICAL\x10\x01\x12\x17\n" +
	"\x13BUCKET_TYPE_VIRTUAL\x10\x02\x12\x16\n" +
	"\x12BUCKET_TYPE_INCOME\x10\x03\x12\x17\n" +
	"\x13BUCKET_TYPE_EXPENSE\x10\x04\x12\x16\n" +
	"\x12BUCKET_TYPE_EQUITY\x10\x052\x85\x05\n" +
	"\x11WealthFlowService\x12W\n" +
	"\fRecordInflow\x12\".wealthflow.v1.RecordInflowRequest\x1a#.wealthflow.v1.RecordInflowResponse\x12Q\n" +
	"\n" +
	"LogExpense\x12 .wealthflow.v1.LogExpenseRequest\x1a!.wealthflow.v1.LogExpenseResponse\x12c\n" +
	"\x10UpdateInvestment\x12&.wealthflow.v1.UpdateInvestmentRequest\x1a'.wealthflow.v1.UpdateInvestmentResponse\x12T\n" +
	"\vListBuckets\x12!.wealthflow.v1.ListBucketsRequest\x1a\".wealthflow.v1.ListBucketsResponse\x12c\n" +
	"\x10ListTransactions\x12&.wealthflow.v1.ListTransactionsRequest\x1a'.wealthflow.v1.ListTransactionsResponse\x12T\n" +
	"\vGetNetWorth\x12!.wealthflow.v1.GetNetWorthRequest\x1a\".wealthflow.v1.GetNetWorthResponse\x12N\n" +
	"\tGetBucket\x12\x1f.wealthflow.v1.GetBucketRequest\x1a .wealthflow.v1.GetBucketResponseBJZHgithub.com/simaogato/wealthflow-backend/proto/wealthflow/v1;wealthflowv1b\x06proto3"

var (
	file_wealthflow_v1_service_proto_rawDescOnce sync.Once
	file_wealthflow_v1_service_proto_rawDescData []byte
)

func file_wealthflow_v1_service_proto_rawDescGZIP() []byte {
	file_wealthflow_v1_service_proto_rawDescOnce.Do(func() {
		file_wealthflow_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wealthflow_v1_service_proto_rawDesc), len(file_wealthflow_v1_service_proto_rawDesc)))
	})
	return file_wealthflow_v1_service_proto_rawDescData
}

var file_wealthflow_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wealthflow_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_wealthflow_v1_service_proto_goTypes = []any{
	(BucketType)(0),                  // 0: wealthflow.v1.BucketType
	(*RecordInflowRequest)(nil),      // 1: wealthflow.v1.RecordInflowRequest
	(*RecordInflowResponse)(nil),     // 2: wealthflow.v1.RecordInflowResponse
	(*LogExpenseRequest)(nil),        // 3: wealthflow.v1.LogExpenseRequest
	(*LogExpenseResponse)(nil),       // 4: wealthflow.v1.LogExpenseResponse
	(*UpdateInvestmentRequest)(nil),  // 5: wealthflow.v1.UpdateInvestmentRequest
	(*UpdateInvestmentResponse)(nil), // 6: wealthflow.v1.UpdateInvestmentResponse
	(*ListBucketsRequest)(nil),       // 7: wealthflow.v1.ListBucketsRequest
	(*ListBucketsResponse)(nil),      // 8: wealthflow.v1.ListBucketsResponse
	(*Bucket)(nil),                   // 9: wealthflow.v1.Bucket
	(*ListTransactionsRequest)(nil),  // 10: wealthflow.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil), // 11: wealthflow.v1.ListTransactionsResponse
	(*Transaction)(nil),              // 12: wealthflow.v1.Transaction
	(*GetNetWorthRequest)(nil),       // 13: wealthflow.v1.GetNetWorthRequest
	(*GetNetWorthResponse)(nil),      // 14: wealthflow.v1.GetNetWorthResponse
	(*GetBucketRequest)(nil),         // 15: wealthflow.v1.GetBucketRequest
	(*GetBucketResponse)(nil),        // 16: wealthflow.v1.GetBucketResponse
	(*timestamppb.Timestamp)(nil),    // 17: google.protobuf.Timestamp
}
var file_wealthflow_v1_service_proto_depIdxs = []int32{
	17, // 0: wealthflow.v1.RecordInflowRequest.date:type_name -> google.protobuf.Timestamp
	17, // 1: wealthflow.v1.RecordInflowResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: wealthflow.v1.LogExpenseRequest.date:type_name -> google.protobuf.Timestamp
	17, // 3: wealthflow.v1.LogExpenseResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: wealthflow.v1.UpdateInvestmentRequest.date:type_name -> google.protobuf.Timestamp
	17, // 5: wealthflow.v1.UpdateInvestmentResponse.created_at:type_name -> google.protobuf.Timestamp
	9,  // 6: wealthflow.v1.ListBucketsResponse.buckets:type_name -> wealthflow.v1.Bucket
	0,  // 7: wealthflow.v1.Bucket.type:type_name -> wealthflow.v1.BucketType
	12, // 8: wealthflow.v1.ListTransactionsResponse.transactions:type_name -> wealthflow.v1.Transaction
	17, // 9: wealthflow.v1.Transaction.date:type_name -> google.protobuf.Timestamp
	9,  // 10: wealthflow.v1.GetBucketResponse.bucket:type_name -> wealthflow.v1.Bucket
	1,  // 11: wealthflow.v1.WealthFlowService.RecordInflow:input_type -> wealthflow.v1.RecordInflowRequest
	3,  // 12: wealthflow.v1.WealthFlowService.LogExpense:input_type -> wealthflow.v1.LogExpenseRequest
	5,  // 13: wealthflow.v1.WealthFlowService.UpdateInvestment:input_type -> wealthflow.v1.UpdateInvestmentRequest
	7,  // 14: wealthflow.v1.WealthFlowService.ListBuckets:input_type -> wealthflow.v1.ListBucketsRequest
	10, // 15: wealthflow.v1.WealthFlowService.ListTransactions:input_type -> wealthflow.v1.ListTransactionsRequest
	13, // 16: wealthflow.v1.WealthFlowService.GetNetWorth:input_type -> wealthflow.v1.GetNetWorthRequest
	15, // 17: wealthflow.v1.WealthFlowService.GetBucket:input_type -> wealthflow.v1.GetBucketRequest
	2,  // 18: wealthflow.v1.WealthFlowService.RecordInflow:output_type -> wealthflow.v1.RecordInflowResponse
	4,  // 19: wealthflow.v1.WealthFlowService.LogExpense:output_type -> wealthflow.v1.LogExpenseResponse
	6,  // 20: wealthflow.v1.WealthFlowService.UpdateInvestment:output_type -> wealthflow.v1.UpdateInvestmentResponse
	8,  // 21: wealthflow.v1.WealthFlowService.ListBuckets:output_type -> wealthflow.v1.ListBucketsResponse
	11, // 22: wealthflow.v1.WealthFlowService.ListTransactions:output_type -> wealthflow.v1.ListTransactionsResponse
	14, // 23: wealthflow.v1.WealthFlowService.GetNetWorth:output_type -> wealthflow.v1.GetNetWorthResponse
	16, // 24: wealthflow.v1.WealthFlowService.GetBucket:output_type -> wealthflow.v1.GetBucketResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wealthflow_v1_service_proto_init() }
func file_wealthflow_v1_service_proto_init() {
	if File_wealthflow_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wealthflow_v1_service_proto_rawDesc), len(file_wealthflow_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wealthflow_v1_service_proto_goTypes,
		DependencyIndexes: file_wealthflow_v1_service_proto_depIdxs,
		EnumInfos:         file_wealthflow_v1_service_proto_enumTypes,
		MessageInfos:      file_wealthflow_v1_service_proto_msgTypes,
	}.Build()
	File_wealthflow_v1_service_proto = out.File
	file_wealthflow_v1_service_proto_goTypes = nil
	file_wealthflow_v1_service_proto_depIdxs = nil
}
