// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: wealthflow/v1/service.proto

package wealthflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordInflowRequest represents an income/inflow transaction
type RecordInflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount as a decimal string (e.g., "1000.50") to preserve precision
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Description of the inflow transaction
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Source bucket ID (UUID as string) - typically an Income or Physical bucket
	SourceBucketId string `protobuf:"bytes,3,opt,name=source_bucket_id,json=sourceBucketId,proto3" json:"source_bucket_id,omitempty"`
	// If true, this is an external inflow that triggers Split Rule Engine
	IsExternal bool `protobuf:"varint,4,opt,name=is_external,json=isExternal,proto3" json:"is_external,omitempty"`
	// Optional: Transaction date (defaults to server time if not provided)
	Date          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordInflowRequest) Reset() {
	*x = RecordInflowRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordInflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordInflowRequest) ProtoMessage() {}

func (x *RecordInflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordInflowRequest.ProtoReflect.Descriptor instead.
func (*RecordInflowRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RecordInflowRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RecordInflowRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecordInflowRequest) GetSourceBucketId() string {
	if x != nil {
		return x.SourceBucketId
	}
	return ""
}

func (x *RecordInflowRequest) GetIsExternal() bool {
	if x != nil {
		return x.IsExternal
	}
	return false
}

func (x *RecordInflowRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// RecordInflowResponse returns the created transaction details
type RecordInflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID (UUID as string)
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Timestamp when the transaction was created
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordInflowResponse) Reset() {
	*x = RecordInflowResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordInflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordInflowResponse) ProtoMessage() {}

func (x *RecordInflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordInflowResponse.ProtoReflect.Descriptor instead.
func (*RecordInflowResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecordInflowResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecordInflowResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// LogExpenseRequest represents an expense transaction
type LogExpenseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount as a decimal string (e.g., "25.99") to preserve precision
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// Description of the expense
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Virtual bucket ID (UUID as string) - the virtual bucket being debited
	VirtualBucketId string `protobuf:"bytes,3,opt,name=virtual_bucket_id,json=virtualBucketId,proto3" json:"virtual_bucket_id,omitempty"`
	// Category bucket ID (UUID as string) - the external expense category
	CategoryBucketId string `protobuf:"bytes,4,opt,name=category_bucket_id,json=categoryBucketId,proto3" json:"category_bucket_id,omitempty"`
	// Optional: Override the physical bucket to credit
	// If not provided, uses the parent physical bucket of virtual_bucket_id
	PhysicalBucketOverrideId string `protobuf:"bytes,5,opt,name=physical_bucket_override_id,json=physicalBucketOverrideId,proto3" json:"physical_bucket_override_id,omitempty"`
	// Optional: Transaction date (defaults to server time if not provided)
	Date          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogExpenseRequest) Reset() {
	*x = LogExpenseRequest{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogExpenseRequest) ProtoMessage() {}

func (x *LogExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogExpenseRequest.ProtoReflect.Descriptor instead.
func (*LogExpenseRequest) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogExpenseRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LogExpenseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LogExpenseRequest) GetVirtualBucketId() string {
	if x != nil {
		return x.VirtualBucketId
	}
	return ""
}

func (x *LogExpenseRequest) GetCategoryBucketId() string {
	if x != nil {
		return x.CategoryBucketId
	}
	return ""
}

func (x *LogExpenseRequest) GetPhysicalBucketOverrideId() string {
	if x != nil {
		return x.PhysicalBucketOverrideId
	}
	return ""
}

func (x *LogExpenseRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

// LogExpenseResponse returns the created transaction details
type LogExpenseResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transaction ID (UUID as string)
	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Timestamp when the transaction was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Physical bucket ID that was actually credited (useful when override was used)
	PhysicalBucketId string `protobuf:"bytes,3,opt,name=physical_bucket_id,json=physicalBucketId,proto3" json:"physical_bucket_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogExpenseResponse) Reset() {
	*x = LogExpenseResponse{}
	mi := &file_wealthflow_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogExpenseResponse) ProtoMessage() {}

func (x *LogExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wealthflow_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogExpenseResponse.ProtoReflect.Descriptor instead.
func (*LogExpenseResponse) Descriptor() ([]byte, []int) {
	return file_wealthflow_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *LogExpenseResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *LogExpenseResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LogExpenseResponse) GetPhysicalBucketId() string {
	if x != nil {
		return x.PhysicalBucketId
	}
	return ""
}

var File_wealthflow_v1_service_proto protoreflect.FileDescriptor

const file_wealthflow_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bwealthflow/v1/service.proto\x12\rwealthflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\x13RecordInflowRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\x10source_bucket_id\x18\x03 \x01(\tR\x0esourceBucketId\x12\x1f\n" +
	"\vis_external\x18\x04 \x01(\bR\n" +
	"isExternal\x12.\n" +
	"\x04date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"x\n" +
	"\x14RecordInflowResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x96\x02\n" +
	"\x11LogExpenseRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11virtual_bucket_id\x18\x03 \x01(\tR\x0fvirtualBucketId\x12,\n" +
	"\x12category_bucket_id\x18\x04 \x01(\tR\x10categoryBucketId\x12=\n" +
	"\x1bphysical_bucket_override_id\x18\x05 \x01(\tR\x18physicalBucketOverrideId\x12.\n" +
	"\x04date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xa4\x01\n" +
	"\x12LogExpenseResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12,\n" +
	"\x12physical_bucket_id\x18\x03 \x01(\tR\x10physicalBucketId2\xbf\x01\n" +
	"\x11WealthFlowService\x12W\n" +
	"\fRecordInflow\x12\".wealthflow.v1.RecordInflowRequest\x1a#.wealthflow.v1.RecordInflowResponse\x12Q\n" +
	"\n" +
	"LogExpense\x12 .wealthflow.v1.LogExpenseRequest\x1a!.wealthflow.v1.LogExpenseResponseBJZHgithub.com/simaogato/wealthflow-backend/proto/wealthflow/v1;wealthflowv1b\x06proto3"

var (
	file_wealthflow_v1_service_proto_rawDescOnce sync.Once
	file_wealthflow_v1_service_proto_rawDescData []byte
)

func file_wealthflow_v1_service_proto_rawDescGZIP() []byte {
	file_wealthflow_v1_service_proto_rawDescOnce.Do(func() {
		file_wealthflow_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wealthflow_v1_service_proto_rawDesc), len(file_wealthflow_v1_service_proto_rawDesc)))
	})
	return file_wealthflow_v1_service_proto_rawDescData
}

var file_wealthflow_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wealthflow_v1_service_proto_goTypes = []any{
	(*RecordInflowRequest)(nil),   // 0: wealthflow.v1.RecordInflowRequest
	(*RecordInflowResponse)(nil),  // 1: wealthflow.v1.RecordInflowResponse
	(*LogExpenseRequest)(nil),     // 2: wealthflow.v1.LogExpenseRequest
	(*LogExpenseResponse)(nil),    // 3: wealthflow.v1.LogExpenseResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_wealthflow_v1_service_proto_depIdxs = []int32{
	4, // 0: wealthflow.v1.RecordInflowRequest.date:type_name -> google.protobuf.Timestamp
	4, // 1: wealthflow.v1.RecordInflowResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: wealthflow.v1.LogExpenseRequest.date:type_name -> google.protobuf.Timestamp
	4, // 3: wealthflow.v1.LogExpenseResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: wealthflow.v1.WealthFlowService.RecordInflow:input_type -> wealthflow.v1.RecordInflowRequest
	2, // 5: wealthflow.v1.WealthFlowService.LogExpense:input_type -> wealthflow.v1.LogExpenseRequest
	1, // 6: wealthflow.v1.WealthFlowService.RecordInflow:output_type -> wealthflow.v1.RecordInflowResponse
	3, // 7: wealthflow.v1.WealthFlowService.LogExpense:output_type -> wealthflow.v1.LogExpenseResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_wealthflow_v1_service_proto_init() }
func file_wealthflow_v1_service_proto_init() {
	if File_wealthflow_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wealthflow_v1_service_proto_rawDesc), len(file_wealthflow_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wealthflow_v1_service_proto_goTypes,
		DependencyIndexes: file_wealthflow_v1_service_proto_depIdxs,
		MessageInfos:      file_wealthflow_v1_service_proto_msgTypes,
	}.Build()
	File_wealthflow_v1_service_proto = out.File
	file_wealthflow_v1_service_proto_goTypes = nil
	file_wealthflow_v1_service_proto_depIdxs = nil
}
